services:
  mongo:
    image: mongo:7.0
    container_name: careflow_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - careflow_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: careflow_app
    restart: always
    ports:
      - "5001:3001"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      MONGO_URI: mongodb://mongo:27017/careflowdb 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./certs:/certs:ro
    depends_on:
      - mongo
    networks:
      - careflow_network
    command: ["sh", "-c", "sleep 5 && npm run dev"]

volumes:
  mongo_data:

networks:
  careflow_network:
    driver: bridge